import { getSupabase } from "@/lib/supabase";

// GET — today's tasks generated by the daily_agent (project_notes with source=daily_agent from today)
export async function GET() {
  const sb = getSupabase();
  if (!sb) return Response.json({ data: [] });

  const startOfToday = new Date();
  startOfToday.setHours(0, 0, 0, 0);

  const { data: notes } = await sb
    .from("project_notes")
    .select("id, project_id, content, created_at, source")
    .eq("source", "daily_agent")
    .gte("created_at", startOfToday.toISOString())
    .order("created_at", { ascending: false })
    .limit(20);

  const tasks = (notes || []).map((n: { id: string; content: string; created_at: string }) => {
    const text = n.content.replace(/^\[.*?\]\s*/, "").split("\n")[0].slice(0, 120);
    return {
      id: n.id,
      text,
      done: false,
      priority: "medium" as const,
      created_at: n.created_at,
    };
  });

  return Response.json({ data: tasks });
}
