import { getSupabaseAdmin } from "@/lib/supabase";

interface AgentReport {
  agent: string;
  output: string;
}

function generateMarkdown(agentName: string, role: string, projectName: string, output: string): string {
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  // Extract sections from the output or create structure
  const lines = output.split("\n");
  const hasHeaders = lines.some((l) => l.startsWith("**") || l.startsWith("#"));

  let structured = output;
  if (!hasHeaders) {
    structured = `## Key Findings\n\n${output}`;
  }

  return `# ${agentName} — ${role}
**Project:** ${projectName}
**Date:** ${date}
**Generated by:** JARVIS War Room

---

## Executive Summary

${structured.slice(0, 500)}${structured.length > 500 ? "..." : ""}

---

${structured}

---

## Next Steps

*Review findings above and discuss with the team. Run a refresh when new context is available.*

---
*Generated by JARVIS PE Business Empire — War Room Report System*
`;
}

function markdownToHtml(markdown: string): string {
  let html = markdown
    .replace(/^# (.+)$/gm, '<h1 style="color:#6366f1;border-bottom:2px solid #6366f1;padding-bottom:8px">$1</h1>')
    .replace(/^## (.+)$/gm, '<h2 style="color:#e2e8f0;margin-top:24px">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 style="color:#94a3b8">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^- (.+)$/gm, '<li style="margin:4px 0">$1</li>')
    .replace(/^---$/gm, '<hr style="border-color:#1e1e2e;margin:24px 0">')
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br>");

  // Wrap list items
  html = html.replace(/(<li[^>]*>.*?<\/li>)+/g, '<ul style="padding-left:20px;margin:12px 0">$&</ul>');

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0a0a0f; color: #e2e8f0; padding: 40px; max-width: 800px; margin: 0 auto; line-height: 1.6; }
  h1 { font-size: 24px; }
  h2 { font-size: 18px; }
  h3 { font-size: 15px; }
  p { margin: 8px 0; }
  strong { color: #f8fafc; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th { background: #1e1e2e; color: #6366f1; padding: 8px 12px; text-align: left; border: 1px solid #2d2d3d; }
  td { padding: 8px 12px; border: 1px solid #1e1e2e; }
</style></head>
<body><p>${html}</p></body>
</html>`;
}

const ROLE_MAP: Record<string, string> = {
  cfo: "Chief Financial Officer",
  cto: "Chief Technology Officer",
  coo: "Chief Operating Officer",
  clo: "Chief Legal Officer",
  chro: "Chief HR Officer",
  cmo: "Chief Marketing Officer",
  cso: "Chief Sales Officer",
  vp_product: "VP of Product",
  vp_engineering: "VP of Engineering",
  vp_sales: "VP of Sales",
  vp_operations: "VP of Operations",
  head_cx: "Head of Customer Experience",
  head_of_recruiting: "Head of Recruiting",
  investor_relations: "Investor Relations",
  head_of_growth: "Head of Growth",
  head_of_content: "Head of Content",
  head_of_design: "Head of Design",
  head_of_pr: "Head of PR",
  customer_success: "Customer Success",
  data_analytics: "Data Analytics",
  orchestrator: "Master Orchestrator",
};

export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const sb = getSupabaseAdmin();
  if (!sb) return Response.json({ error: "Supabase not configured" }, { status: 500 });

  const { results, jarvisSummary, projectName } = await request.json() as {
    results: Record<string, AgentReport>;
    jarvisSummary: string;
    projectName: string;
  };

  if (!results || !projectName) {
    return Response.json({ error: "results and projectName are required" }, { status: 400 });
  }

  const generatedFiles: { agentName: string; fileName: string; url: string }[] = [];
  const timestamp = Date.now();
  const safeProjectName = projectName.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 30);

  // Generate reports for each agent
  for (const [key, report] of Object.entries(results)) {
    const role = ROLE_MAP[key] || report.agent;
    const markdown = generateMarkdown(report.agent, role, projectName, report.output);
    const html = markdownToHtml(markdown);
    const fileName = `${safeProjectName}/${timestamp}_${key}.html`;

    // Save HTML report to Supabase storage
    const { error: uploadErr } = await sb.storage
      .from("war-room-reports")
      .upload(fileName, html, { contentType: "text/html", upsert: true });

    if (uploadErr) {
      // If bucket doesn't exist, save as project note instead
      const noteId = `wr-pdf-${key}-${timestamp}`;
      await sb.from("project_notes").insert({
        id: noteId,
        project_id: id,
        content: `[War Room Report — ${report.agent}]\n${markdown}`,
        created_at: new Date().toISOString(),
      });
      generatedFiles.push({ agentName: report.agent, fileName: `${key}_report.md`, url: `/ideas/${id}?tab=Notes` });
    } else {
      const { data: urlData } = sb.storage.from("war-room-reports").getPublicUrl(fileName);
      generatedFiles.push({ agentName: report.agent, fileName, url: urlData.publicUrl });
    }
  }

  // Generate Jarvis Summary report
  if (jarvisSummary) {
    const summaryMd = generateMarkdown("JARVIS", "Master Orchestrator Summary", projectName, jarvisSummary);
    const summaryHtml = markdownToHtml(summaryMd);
    const summaryFile = `${safeProjectName}/${timestamp}_jarvis_summary.html`;

    const { error: sumErr } = await sb.storage
      .from("war-room-reports")
      .upload(summaryFile, summaryHtml, { contentType: "text/html", upsert: true });

    if (sumErr) {
      await sb.from("project_notes").insert({
        id: `wr-pdf-summary-${timestamp}`,
        project_id: id,
        content: `[War Room Report — JARVIS Summary]\n${summaryMd}`,
        created_at: new Date().toISOString(),
      });
      generatedFiles.push({ agentName: "JARVIS Summary", fileName: "jarvis_summary.md", url: `/ideas/${id}?tab=Notes` });
    } else {
      const { data: urlData } = sb.storage.from("war-room-reports").getPublicUrl(summaryFile);
      generatedFiles.push({ agentName: "JARVIS Summary", fileName: summaryFile, url: urlData.publicUrl });
    }
  }

  return Response.json({
    ok: true,
    reports: generatedFiles,
    totalReports: generatedFiles.length,
  });
}
